nodeLinker: node-modules

npmRegistries:
  'https://userway-384064702811.d.codeartifact.us-west-2.amazonaws.com/npm/userway-npm/':
    npmAlwaysAuth: true

npmRegistryServer: 'https://userway-384064702811.d.codeartifact.us-west-2.amazonaws.com/npm/userway-npm/'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-aws-codeartifact.cjs
    spec: 'https://raw.githubusercontent.com/mhassan1/yarn-plugin-aws-codeartifact/v0.12.0/bundles/@yarnpkg/plugin-aws-codeartifact.js'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.3.1.cjs
