version: '3'

services:

  # http://localhost:4200/
  dev:
    container_name: sample-cypress-project-dev
    image: userway/sample-cypress-project
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - '4200:4200'
    restart: unless-stopped
